name: kadai_info_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.7
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/
    - .env